[theme]
primaryColor="#005866"  # Turquoise
backgroundColor="#00012b"
secondaryBackgroundColor="#03292f"
textColor="#FFFFFF"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats = false

[global]
developmentMode = false
