[theme]
primaryColor="#00CED1"  # Turquoise
backgroundColor="#2F2F2F"
secondaryBackgroundColor="#404040"
textColor="#FFFFFF"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=false

[browser]
gatherUsageStats = false

[global]
developmentMode = false
